import { ComponentDef } from '@/data/components';
import { AssignmentResult, substituteGPIO } from './gpio';

export interface PiModel {
  id: string; name: string; ram: string;
  gpio: number; usb3: boolean; gbe: boolean;
  maxCurrent: number; icon: string;
}

function uniqueLibs(components: ComponentDef[]): string[] {
  const seen: Record<string, boolean> = {};
  const result: string[] = [];
  for (const c of components) {
    if (c.library !== 'n/a' && !seen[c.library]) {
      seen[c.library] = true;
      result.push(c.library);
    }
  }
  return result;
}

export function generateCode(
  components: ComponentDef[],
  result: AssignmentResult,
  type: 'gpiozero' | 'rpigpio',
  projectName: string,
  pi: PiModel | null,
): string {
  if (!components.length) return '# No components selected';
  const lines = [
    `# ${projectName}`,
    `# Generated by PiBuilder AI`,
    `# Pi: ${pi?.name ?? 'Unknown'}`,
    `# Components: ${components.map(c => c.name).join(', ')}`,
    '',
  ];
  if (type === 'gpiozero') {
    lines.push('# Install dependencies (see bottom of file)', '');
  } else {
    lines.push('import RPi.GPIO as GPIO', 'GPIO.setmode(GPIO.BCM)', '');
  }
  for (const comp of components) {
    const asgn = result.assigned[comp.id];
    if (!asgn) continue;
    lines.push(`# ── ${comp.name} (${asgn.label}) ──`);
    const raw = comp.code[type] ?? comp.code.gpiozero;
    lines.push(substituteGPIO(raw, asgn), '');
  }
  const libs = uniqueLibs(components);
  lines.push('# ── Install dependencies ──');
  libs.forEach(l => lines.push(`# pip install ${l}`));
  return lines.join('\n');
}

export function generateDocs(
  components: ComponentDef[],
  result: AssignmentResult,
  projectName: string,
  pi: PiModel | null,
): string {
  const totalMa = components.reduce((s, c) => s + c.current_ma, 0);
  const lines: string[] = [
    `# ${projectName}`,
    `> Generated by PiBuilder AI`,
    '',
    `## Hardware`,
    `| | |`,
    `|---|---|`,
    `| Pi Model | ${pi?.name ?? 'Unknown'} |`,
    `| Components | ${components.length} |`,
    `| Total Current | ~${totalMa}mA |`,
    '',
    '## Parts List',
    ...components.map(c => `- ${c.icon} **${c.name}** — ${c.power}, ~${c.current_ma}mA`),
    '- Jumper wires, breadboard',
    ...components.filter(c => c.requires_resistor).map(c => `- ${c.requires_resistor!.value} resistor (for ${c.name})`),
    ...components.filter(c => c.requires_capacitor).map(c => `- ${c.requires_capacitor!.value} capacitor (for ${c.name})`),
    '',
    '## GPIO Assignments',
    ...components.map(c => `- **${c.name}:** ${result.assigned[c.id]?.label ?? 'Unassigned'}`),
    '',
    '## Wiring Instructions',
  ];
  for (const comp of components) {
    const asgn = result.assigned[comp.id];
    if (!asgn) continue;
    lines.push(`\n### ${comp.icon} ${comp.name}`);
    if (comp.notes) lines.push(`> ${comp.notes}`, '');
    comp.wiring.forEach(w => {
      const from = substituteGPIO(w.from, asgn);
      lines.push(`- Connect **${from}** → ${w.to}`);
    });
    if (comp.requires_resistor) {
      lines.push(`- Add **${comp.requires_resistor.value}** resistor — ${comp.requires_resistor.placement}`);
    }
    if (comp.requires_capacitor) {
      lines.push(`- Add **${comp.requires_capacitor.value}** capacitor — ${comp.requires_capacitor.placement}`);
    }
  }
  lines.push('', '## Python Code', '```python', generateCode(components, result, 'gpiozero', projectName, pi), '```', '');
  lines.push('## Install Libraries', '```bash');
  uniqueLibs(components).forEach(l => lines.push(`pip install ${l}`));
  lines.push('```', '', '## Troubleshooting',
    '- **No response:** Check wiring polarity and power supply',
    '- **ImportError:** Run pip install for the required library',
    '- **GPIO busy error:** Run GPIO.cleanup() or reboot',
    '- **Component gets hot:** Check voltage levels (3.3V vs 5V)',
  );
  return lines.join('\n');
}
